Repository hmcts/disposer-idam-user, pull requests merged in 2023-10, with the labels that each got.

#126 LAU-754 Token generation before application run
  src/functionalTest/java/uk/gov/hmcts/reform/idam/helpers/IdamUserDataProvider.java
  src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java
  src/main/java/uk/gov/hmcts/reform/idam/service/aop/MethodRetryAspect.java
  src/main/java/uk/gov/hmcts/reform/idam/util/SecurityUtil.java
  src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-126

#128 LAU-755 Add Simulation mode
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/SpringBootIntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/UserDisposerSteps.java
  src/integrationTest/java/uk/gov/hmcts/reform/idam/bdd/WireMockStubs.java
  src/integrationTest/resources/features/user_disposer.feature
  src/main/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolver.java
  src/main/java/uk/gov/hmcts/reform/idam/service/DeleteUserService.java
  src/main/resources/application.yaml
  src/test/java/uk/gov/hmcts/reform/idam/parameter/ParameterResolverTest.java
  src/test/java/uk/gov/hmcts/reform/idam/service/DeleteUserServiceTest.java
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-128

#141 LAU-762 added reports
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-141

#143 LAU-762 functional test report reaarange
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
  src/functionalTest/resources/application-functional.yaml
Labels: ns:disposer, prd:disposer, enable_keep_helm, rel:disposer-idam-user-pr-143

#144 LAU-762 remove functional test report
  Jenkinsfile_CNP
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-144

#134 LAU-753 Idam User Disposer Summary
  src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java
  src/main/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtils.java
  src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
  src/test/java/uk/gov/hmcts/reform/idam/util/LoggingSummaryUtilsTest.java
Labels: ns:disposer, prd:disposer, enable_keep_helm, rel:disposer-idam-user-pr-134

#150 LAU-753 Disposer Idam symmary with correct batch users
  src/main/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerService.java
  src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java
  src/test/java/uk/gov/hmcts/reform/idam/service/IdamUserDisposerServiceTest.java
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-150

#145 Lau 762
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  build.gradle
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-145

#151 LAU-762 disable funstional test on nightly build
  Jenkinsfile_nightly
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-151

#152 LAU-764 adding catalog-info.yaml
  catalog-info.yaml
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-152

#153 LAU-764 upgrading chart version
  charts/disposer-idam-user/Chart.yaml
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-153

#142 LAU-760 delete user that has one and only citizen role
  src/functionalTest/java/uk/gov/hmcts/reform/idam/UserDeletionFunctionalTest.java
  src/integrationTest/resources/wiremock/__files/staleUsersPage1.json
  src/main/java/uk/gov/hmcts/reform/idam/service/StaleUsersService.java
  src/test/java/uk/gov/hmcts/reform/idam/service/StaleUsersServiceTest.java
  stale-users.json
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-142

#40 Enable Fortify scan Idam-user-disposer-Fortify client
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-40

#160 LAU-788 update disposer-idam-user README
  README.md
Labels: ns:disposer, prd:disposer, rel:disposer-idam-user-pr-160
